"""add normalized records table

Revision ID: 934f476aac3d
Revises: e164e38a4809
Create Date: 2026-05-31 18:10:18.068407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934f476aac3d'
down_revision: Union[str, Sequence[str], None] = 'e164e38a4809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_records',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=False),
    sa.Column('record_category', sa.String(length=50), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('normalization_status', sa.String(length=20), nullable=False),
    sa.Column('normalization_confidence', sa.Float(), nullable=True),
    sa.Column('normalization_errors', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['extracted_records.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_records_document_id'), 'normalized_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_normalization_status'), 'normalized_records', ['normalization_status'], unique=False)
    op.create_index(op.f('ix_normalized_records_record_category'), 'normalized_records', ['record_category'], unique=False)
    op.create_index(op.f('ix_normalized_records_source_record_id'), 'normalized_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_workspace_id'), 'normalized_records', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_records_workspace_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_source_record_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_record_category'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_normalization_status'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_document_id'), table_name='normalized_records')
    op.drop_table('normalized_records')
    # ### end Alembic commands ###
