"""add documents table and storage metadata

Revision ID: a546d82f7500
Revises: bbe71c580805
Create Date: 2026-05-28 17:49:20.310022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a546d82f7500'
down_revision: Union[str, Sequence[str], None] = 'bbe71c580805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('document_type', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('upload_source', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
