"""add document classification fields

Revision ID: e164e38a4809
Revises: fe43c1f1862c
Create Date: 2026-05-30 18:29:56.130215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e164e38a4809'
down_revision: Union[str, Sequence[str], None] = 'fe43c1f1862c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('classification_method', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('classification_reason', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classified_at')
    op.drop_column('documents', 'classification_reason')
    op.drop_column('documents', 'classification_method')
    op.drop_column('documents', 'classification_confidence')
    # ### end Alembic commands ###
