"""add_extracted_records_table

Revision ID: fe43c1f1862c
Revises: e954a288bd96
Create Date: 2026-05-30 16:54:42.838602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe43c1f1862c'
down_revision: Union[str, Sequence[str], None] = 'e954a288bd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_records',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_records_document_id'), 'extracted_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_records_record_type'), 'extracted_records', ['record_type'], unique=False)
    op.create_index(op.f('ix_extracted_records_workspace_id'), 'extracted_records', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_records_workspace_id'), table_name='extracted_records')
    op.drop_index(op.f('ix_extracted_records_record_type'), table_name='extracted_records')
    op.drop_index(op.f('ix_extracted_records_document_id'), table_name='extracted_records')
    op.drop_table('extracted_records')
    # ### end Alembic commands ###
