"""Application-wide constants."""

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
STATUS_ARCHIVED = "archived"

WORKSPACE_ROLE_OWNER = "owner"
WORKSPACE_ROLE_ADMIN = "admin"
WORKSPACE_ROLE_EDITOR = "editor"
WORKSPACE_ROLE_VIEWER = "viewer"

ALLOWED_WORKSPACE_MEMBER_ROLES = {
    WORKSPACE_ROLE_OWNER,
    WORKSPACE_ROLE_ADMIN,
    WORKSPACE_ROLE_EDITOR,
    WORKSPACE_ROLE_VIEWER,
}

WORKSPACE_READ_ROLES = {
    WORKSPACE_ROLE_OWNER,
    WORKSPACE_ROLE_ADMIN,
    WORKSPACE_ROLE_EDITOR,
    WORKSPACE_ROLE_VIEWER,
}
WORKSPACE_WRITE_ROLES = {
    WORKSPACE_ROLE_OWNER,
    WORKSPACE_ROLE_ADMIN,
    WORKSPACE_ROLE_EDITOR,
}
WORKSPACE_ADMIN_ROLES = {
    WORKSPACE_ROLE_OWNER,
    WORKSPACE_ROLE_ADMIN,
}

AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
AUTH_TOKEN_TYPE_BEARER = "bearer"

WORKSPACE_ACCESS_DENIED = "WORKSPACE_ACCESS_DENIED"
WORKSPACE_ROLE_REQUIRED = "WORKSPACE_ROLE_REQUIRED"
WORKSPACE_MEMBER_NOT_FOUND = "WORKSPACE_MEMBER_NOT_FOUND"
WORKSPACE_LAST_OWNER_REQUIRED = "WORKSPACE_LAST_OWNER_REQUIRED"
WORKSPACE_MEMBER_ALREADY_EXISTS = "WORKSPACE_MEMBER_ALREADY_EXISTS"

USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
USER_NOT_FOUND = "USER_NOT_FOUND"

DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_PROCESSED = "processed"
DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUS_DELETED = "deleted"

DOCUMENT_TYPE_VENDOR_LEDGER = "vendor_ledger"
DOCUMENT_TYPE_TDS_WORKING = "tds_working"
DOCUMENT_TYPE_VENDOR_MASTER = "vendor_master"
DOCUMENT_TYPE_INVOICE = "invoice"
DOCUMENT_TYPE_TDS_CHALLAN = "tds_challan"
DOCUMENT_TYPE_FORM_26AS = "form_26as"
DOCUMENT_TYPE_UNKNOWN = "unknown"

NORMALIZED_CATEGORY_VENDOR_MASTER = "vendor_master"
NORMALIZED_CATEGORY_VENDOR_LEDGER = "vendor_ledger"
NORMALIZED_CATEGORY_TDS_WORKING = "tds_working"
NORMALIZED_CATEGORY_TDS_CHALLAN = "tds_challan"
NORMALIZED_CATEGORY_FORM_26AS = "form_26as"
NORMALIZED_CATEGORY_INVOICE = "invoice"
NORMALIZED_CATEGORY_UNKNOWN = "unknown"

DOCUMENT_UPLOAD_SOURCE_MANUAL = "manual"

STORAGE_BACKEND_LOCAL = "local"
STORAGE_BACKEND_S3 = "s3"

JOB_STATUS_PENDING = "pending"
JOB_STATUS_STARTED = "started"
JOB_STATUS_EXTRACTING = "extracting"
JOB_STATUS_CLASSIFYING = "classifying"
JOB_STATUS_NORMALIZING = "normalizing"
JOB_STATUS_EMBEDDING = "embedding"
JOB_STATUS_RUNNING_RISK_CHECKS = "running_risk_checks"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"

NORMALIZATION_STATUS_NORMALIZED = "normalized"
NORMALIZATION_STATUS_PARTIAL = "partial"
NORMALIZATION_STATUS_FAILED = "failed"
NORMALIZATION_STATUS_SKIPPED = "skipped"

JOB_TYPE_DOCUMENT_PROCESSING = "document_processing"

ALLOWED_DOCUMENT_EXTENSIONS = {".pdf", ".xlsx", ".xls", ".csv"}

EXTRACTION_RECORD_TYPE_TEXT = "text"
EXTRACTION_RECORD_TYPE_TABLE_ROW = "table_row"
EXTRACTION_RECORD_TYPE_EXCEL_ROW = "excel_row"
EXTRACTION_RECORD_TYPE_CSV_ROW = "csv_row"
EXTRACTION_RECORD_TYPE_METADATA = "metadata"

EXTRACTION_UNSUPPORTED_FILE_TYPE = "EXTRACTION_UNSUPPORTED_FILE_TYPE"
EXTRACTION_FILE_NOT_FOUND = "EXTRACTION_FILE_NOT_FOUND"
EXTRACTION_STORAGE_BACKEND_UNSUPPORTED = "EXTRACTION_STORAGE_BACKEND_UNSUPPORTED"
EXTRACTION_FAILED = "EXTRACTION_FAILED"
EXTRACTION_NO_CONTENT_FOUND = "EXTRACTION_NO_CONTENT_FOUND"
EXTRACTION_FILE_TOO_LARGE = "EXTRACTION_FILE_TOO_LARGE"
EXTRACTION_TOO_MANY_ROWS = "EXTRACTION_TOO_MANY_ROWS"
EXTRACTION_TOO_MANY_COLUMNS = "EXTRACTION_TOO_MANY_COLUMNS"
EXTRACTION_TOO_MANY_SHEETS = "EXTRACTION_TOO_MANY_SHEETS"
EXTRACTION_TOO_MANY_PAGES = "EXTRACTION_TOO_MANY_PAGES"

CLASSIFICATION_FAILED = "CLASSIFICATION_FAILED"
CLASSIFICATION_REQUIRES_EXTRACTION = "CLASSIFICATION_REQUIRES_EXTRACTION"
CLASSIFICATION_DOCUMENT_NOT_FOUND = "CLASSIFICATION_DOCUMENT_NOT_FOUND"
CLASSIFICATION_DOCUMENT_DELETED = "CLASSIFICATION_DOCUMENT_DELETED"

NORMALIZATION_FAILED = "NORMALIZATION_FAILED"
NORMALIZATION_REQUIRES_EXTRACTION = "NORMALIZATION_REQUIRES_EXTRACTION"
NORMALIZATION_REQUIRES_CLASSIFICATION = "NORMALIZATION_REQUIRES_CLASSIFICATION"
NORMALIZATION_UNSUPPORTED_DOCUMENT_TYPE = "NORMALIZATION_UNSUPPORTED_DOCUMENT_TYPE"
NORMALIZATION_DOCUMENT_NOT_FOUND = "NORMALIZATION_DOCUMENT_NOT_FOUND"
NORMALIZATION_DOCUMENT_DELETED = "NORMALIZATION_DOCUMENT_DELETED"
NORMALIZATION_NO_RECORDS_CREATED = "NORMALIZATION_NO_RECORDS_CREATED"

RISK_TYPE_MISSING_PAN = "missing_pan"
RISK_TYPE_DUPLICATE_INVOICE = "duplicate_invoice"
RISK_TYPE_TDS_MISMATCH = "tds_mismatch"
RISK_TYPE_SHORT_DEPOSIT = "short_deposit"
RISK_TYPE_VENDOR_NAME_MISMATCH = "vendor_name_mismatch"
RISK_TYPE_WRONG_TDS_SECTION = "wrong_tds_section"
RISK_TYPE_HIGH_VALUE_TRANSACTION = "high_value_transaction"
RISK_TYPE_MISSING_SUPPORTING_DOCUMENT = "missing_supporting_document"

RISK_RULE_KEY_MISSING_PAN_V1 = "missing_pan_v1"
RISK_RULE_KEY_DUPLICATE_INVOICE_V1 = "duplicate_invoice_v1"
RISK_RULE_KEY_TDS_MISMATCH_V1 = "tds_mismatch_v1"
RISK_RULE_KEY_SHORT_DEPOSIT_V1 = "short_deposit_v1"
RISK_RULE_KEY_VENDOR_NAME_MISMATCH_V1 = "vendor_name_mismatch_v1"
RISK_RULE_KEY_HIGH_VALUE_TRANSACTION_V1 = "high_value_transaction_v1"

RISK_RULE_KEYS_V1 = (
    RISK_RULE_KEY_MISSING_PAN_V1,
    RISK_RULE_KEY_DUPLICATE_INVOICE_V1,
    RISK_RULE_KEY_TDS_MISMATCH_V1,
    RISK_RULE_KEY_SHORT_DEPOSIT_V1,
    RISK_RULE_KEY_VENDOR_NAME_MISMATCH_V1,
    RISK_RULE_KEY_HIGH_VALUE_TRANSACTION_V1,
)

RISK_RULE_KEY_TO_RISK_TYPE = {
    RISK_RULE_KEY_MISSING_PAN_V1: RISK_TYPE_MISSING_PAN,
    RISK_RULE_KEY_DUPLICATE_INVOICE_V1: RISK_TYPE_DUPLICATE_INVOICE,
    RISK_RULE_KEY_TDS_MISMATCH_V1: RISK_TYPE_TDS_MISMATCH,
    RISK_RULE_KEY_SHORT_DEPOSIT_V1: RISK_TYPE_SHORT_DEPOSIT,
    RISK_RULE_KEY_VENDOR_NAME_MISMATCH_V1: RISK_TYPE_VENDOR_NAME_MISMATCH,
    RISK_RULE_KEY_HIGH_VALUE_TRANSACTION_V1: RISK_TYPE_HIGH_VALUE_TRANSACTION,
}

RISK_ENGINE_V1_TYPES = (
    RISK_TYPE_MISSING_PAN,
    RISK_TYPE_DUPLICATE_INVOICE,
    RISK_TYPE_TDS_MISMATCH,
    RISK_TYPE_SHORT_DEPOSIT,
    RISK_TYPE_VENDOR_NAME_MISMATCH,
)

RISK_SEVERITY_LOW = "LOW"
RISK_SEVERITY_MEDIUM = "MEDIUM"
RISK_SEVERITY_HIGH = "HIGH"
RISK_SEVERITY_CRITICAL = "CRITICAL"

ALLOWED_RISK_SEVERITIES = {
    RISK_SEVERITY_LOW,
    RISK_SEVERITY_MEDIUM,
    RISK_SEVERITY_HIGH,
    RISK_SEVERITY_CRITICAL,
}

DEFAULT_SHORT_DEPOSIT_CRITICAL_THRESHOLD = 5000.0
DEFAULT_HIGH_VALUE_TRANSACTION_THRESHOLD = 100000.0

RISK_RULE_CONFIG_DEFAULTS = (
    {
        "rule_key": RISK_RULE_KEY_MISSING_PAN_V1,
        "risk_type": RISK_TYPE_MISSING_PAN,
        "is_enabled": True,
        "severity": RISK_SEVERITY_HIGH,
        "threshold_amount": None,
        "threshold_percent": None,
        "config_data": {},
    },
    {
        "rule_key": RISK_RULE_KEY_DUPLICATE_INVOICE_V1,
        "risk_type": RISK_TYPE_DUPLICATE_INVOICE,
        "is_enabled": True,
        "severity": RISK_SEVERITY_HIGH,
        "threshold_amount": None,
        "threshold_percent": None,
        "config_data": {
            "match_on_vendor": True,
            "match_on_invoice_number": True,
            "match_on_invoice_date": True,
            "match_on_gross_amount": True,
        },
    },
    {
        "rule_key": RISK_RULE_KEY_TDS_MISMATCH_V1,
        "risk_type": RISK_TYPE_TDS_MISMATCH,
        "is_enabled": True,
        "severity": RISK_SEVERITY_HIGH,
        "threshold_amount": 0.0,
        "threshold_percent": None,
        "config_data": {
            "ignore_shortfall_below": 0.0,
        },
    },
    {
        "rule_key": RISK_RULE_KEY_SHORT_DEPOSIT_V1,
        "risk_type": RISK_TYPE_SHORT_DEPOSIT,
        "is_enabled": True,
        "severity": RISK_SEVERITY_HIGH,
        "threshold_amount": DEFAULT_SHORT_DEPOSIT_CRITICAL_THRESHOLD,
        "threshold_percent": None,
        "config_data": {
            "critical_threshold_amount": DEFAULT_SHORT_DEPOSIT_CRITICAL_THRESHOLD,
        },
    },
    {
        "rule_key": RISK_RULE_KEY_VENDOR_NAME_MISMATCH_V1,
        "risk_type": RISK_TYPE_VENDOR_NAME_MISMATCH,
        "is_enabled": True,
        "severity": RISK_SEVERITY_MEDIUM,
        "threshold_amount": None,
        "threshold_percent": None,
        "config_data": {},
    },
    {
        "rule_key": RISK_RULE_KEY_HIGH_VALUE_TRANSACTION_V1,
        "risk_type": RISK_TYPE_HIGH_VALUE_TRANSACTION,
        "is_enabled": False,
        "severity": RISK_SEVERITY_MEDIUM,
        "threshold_amount": DEFAULT_HIGH_VALUE_TRANSACTION_THRESHOLD,
        "threshold_percent": None,
        "config_data": {
            "source_category": NORMALIZED_CATEGORY_VENDOR_LEDGER,
            "amount_field": "gross_amount",
        },
    },
)

RISK_RULE_CONFIG_MUTABLE_FIELDS = {
    "is_enabled",
    "severity",
    "threshold_amount",
    "threshold_percent",
    "config_data",
}

RISK_STATUS_OPEN = "open"
RISK_STATUS_REVIEWED = "reviewed"
RISK_STATUS_RESOLVED = "resolved"
RISK_STATUS_FALSE_POSITIVE = "false_positive"

ALLOWED_RISK_STATUSES = {
    RISK_STATUS_OPEN,
    RISK_STATUS_REVIEWED,
    RISK_STATUS_RESOLVED,
    RISK_STATUS_FALSE_POSITIVE,
}

RISK_ENGINE_FAILED = "RISK_ENGINE_FAILED"
RISK_FINDING_NOT_FOUND = "RISK_FINDING_NOT_FOUND"
RISK_INVALID_STATUS = "RISK_INVALID_STATUS"
RISK_RULE_CONFIG_NOT_FOUND = "RISK_RULE_CONFIG_NOT_FOUND"
RISK_RULE_CONFIG_INVALID_SEVERITY = "RISK_RULE_CONFIG_INVALID_SEVERITY"
RISK_RULE_CONFIG_INVALID_THRESHOLD = "RISK_RULE_CONFIG_INVALID_THRESHOLD"
RISK_RULE_CONFIG_INVALID_CONFIG_DATA = "RISK_RULE_CONFIG_INVALID_CONFIG_DATA"
RISK_RULE_CONFIG_INVALID_RULE_KEY = "RISK_RULE_CONFIG_INVALID_RULE_KEY"
RISK_RULE_CONFIG_IMMUTABLE_FIELD = "RISK_RULE_CONFIG_IMMUTABLE_FIELD"

KNOWLEDGE_SOURCE_TYPE_NORMALIZED_RECORD = "normalized_record"
KNOWLEDGE_SOURCE_TYPE_RISK_FINDING = "risk_finding"
KNOWLEDGE_SOURCE_TYPE_EXTRACTED_RECORD = "extracted_record"

KNOWLEDGE_ALLOWED_SOURCE_TYPES = {
    KNOWLEDGE_SOURCE_TYPE_NORMALIZED_RECORD,
    KNOWLEDGE_SOURCE_TYPE_RISK_FINDING,
    KNOWLEDGE_SOURCE_TYPE_EXTRACTED_RECORD,
}

EMBEDDING_STATUS_PENDING = "pending"
EMBEDDING_STATUS_EMBEDDED = "embedded"
EMBEDDING_STATUS_FAILED = "failed"
EMBEDDING_STATUS_SKIPPED = "skipped"

KNOWLEDGE_ALLOWED_EMBEDDING_STATUSES = {
    EMBEDDING_STATUS_PENDING,
    EMBEDDING_STATUS_EMBEDDED,
    EMBEDDING_STATUS_FAILED,
    EMBEDDING_STATUS_SKIPPED,
}

EMBEDDING_PROVIDER_LOCAL_HASH = "local_hash"

KNOWLEDGE_CHUNK_TYPE_VENDOR_MASTER_RECORD = "vendor_master_record"
KNOWLEDGE_CHUNK_TYPE_VENDOR_LEDGER_RECORD = "vendor_ledger_record"
KNOWLEDGE_CHUNK_TYPE_TDS_WORKING_RECORD = "tds_working_record"
KNOWLEDGE_CHUNK_TYPE_TDS_CHALLAN_RECORD = "tds_challan_record"
KNOWLEDGE_CHUNK_TYPE_FORM_26AS_RECORD = "form_26as_record"
KNOWLEDGE_CHUNK_TYPE_INVOICE_RECORD = "invoice_record"

KNOWLEDGE_QUERY_REQUIRED = "KNOWLEDGE_QUERY_REQUIRED"
KNOWLEDGE_UNSUPPORTED_SOURCE_TYPE = "KNOWLEDGE_UNSUPPORTED_SOURCE_TYPE"
KNOWLEDGE_UNSUPPORTED_EMBEDDING_PROVIDER = "KNOWLEDGE_UNSUPPORTED_EMBEDDING_PROVIDER"
KNOWLEDGE_CHUNK_NOT_FOUND = "KNOWLEDGE_CHUNK_NOT_FOUND"
KNOWLEDGE_INVALID_EMBEDDING_STATUS = "KNOWLEDGE_INVALID_EMBEDDING_STATUS"
KNOWLEDGE_INVALID_RISK_TYPE = "KNOWLEDGE_INVALID_RISK_TYPE"
KNOWLEDGE_SOURCE_NOT_FOUND = "KNOWLEDGE_SOURCE_NOT_FOUND"

RETRIEVAL_MODE_HYBRID = "hybrid"
RETRIEVAL_FUSION_METHOD_RRF = "rrf"

RETRIEVAL_SOURCE_VECTOR = "vector"
RETRIEVAL_SOURCE_KEYWORD = "keyword"
RETRIEVAL_SOURCE_STRUCTURED = "structured"
RETRIEVAL_SOURCE_FUSED = "fused"
RETRIEVAL_SOURCE_RERANKED = "reranked"

RERANKER_PROVIDER_NONE = "none"

LLM_PROVIDER_MOCK = "mock"
LLM_PROVIDER_CEREBRAS = "cerebras"

AGENT_CHAT_FAILED = "AGENT_CHAT_FAILED"
AGENT_CHAT_INVALID_INPUT = "AGENT_CHAT_INVALID_INPUT"
AGENT_CHAT_MESSAGE_REQUIRED = "AGENT_CHAT_MESSAGE_REQUIRED"
AGENT_CHAT_UNSUPPORTED_SOURCE_TYPE = "AGENT_CHAT_UNSUPPORTED_SOURCE_TYPE"
AGENT_CHAT_UNSUPPORTED_LLM_PROVIDER = "AGENT_CHAT_UNSUPPORTED_LLM_PROVIDER"
AGENT_CHAT_CEREBRAS_API_KEY_REQUIRED = "AGENT_CHAT_CEREBRAS_API_KEY_REQUIRED"
AGENT_CHAT_LLM_PROVIDER_ERROR = "AGENT_CHAT_LLM_PROVIDER_ERROR"
AGENT_CHAT_LLM_RATE_LIMITED = "AGENT_CHAT_LLM_RATE_LIMITED"
